# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del programa')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de materia')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de materia')),
                ('creditos', models.PositiveIntegerField(default=1, verbose_name='Número de créditos')),
                ('periodo', models.CharField(blank=True, max_length=20, verbose_name='Periodo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='materias.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
                'ordering': ['nombre'],
            },
        ),
    ]
