# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('encuentro', models.PositiveIntegerField(verbose_name='Número de encuentro')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('excusa', 'Excusa'), ('retardo', 'Retardo')], default='presente', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['-fecha', 'estudiante__nombre_apellido'],
                'unique_together': {('asignacion', 'estudiante', 'encuentro')},
            },
        ),
    ]
