# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del colegio')),
                ('ciudad', models.CharField(default='Barranquilla', max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('tipo_identificacion', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('C.C.', 'Cédula de Ciudadanía')], default='T.I.', max_length=4, verbose_name='Tipo de Identificación')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.colegio', verbose_name='Colegio')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='materias.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
                'ordering': ['nombre_apellido'],
            },
        ),
    ]
