# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(blank=True, max_length=200, verbose_name='Horario')),
                ('periodo', models.CharField(blank=True, max_length=20, verbose_name='Periodo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='espacios.aula', verbose_name='Aula')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='materias.materia', verbose_name='Materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='profesores.profesor', verbose_name='Profesor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='materias.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignaciones',
                'unique_together': {('profesor', 'materia', 'programa', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True, verbose_name='Fecha de matrícula')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matriculas',
                'unique_together': {('estudiante', 'asignacion')},
            },
        ),
    ]
