# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del aula')),
                ('capacidad', models.PositiveIntegerField(default=30, verbose_name='Capacidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='espacios.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aulas',
                'ordering': ['sede', 'nombre'],
            },
        ),
    ]
