# Generated by Django 5.2.15 on 2026-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Se activa automáticamente al crear el usuario. Obliga a cambiar la contraseña en el primer inicio de sesión.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
