# Generated by Django 5.2.15 on 2026-07-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial1', models.FloatField(blank=True, null=True, verbose_name='Parcial 1 (30%)')),
                ('parcial2', models.FloatField(blank=True, null=True, verbose_name='Parcial 2 (30%)')),
                ('parcial3', models.FloatField(blank=True, null=True, verbose_name='Parcial 3 (40%)')),
                ('definitiva', models.FloatField(blank=True, null=True, verbose_name='Definitiva')),
                ('estado', models.CharField(blank=True, max_length=20, verbose_name='Estado')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
                'ordering': ['estudiante__nombre_apellido'],
                'unique_together': {('asignacion', 'estudiante')},
            },
        ),
    ]
